


CREATE TABLE BUS_ENTITY (
  ID INT AUTO_INCREMENT PRIMARY KEY,
  BUS_NUMBER VARCHAR(20) NOT NULL,
  OPERATING_BUS_STAND VARCHAR(20) NOT NULL,
  DEPARTURE_CITY VARCHAR(20) NOT NULL,
  ARRIVAL_CITY VARCHAR(20) NOT NULL,
  DATE_OF_DEPARTURE DATE NOT NULL,
  ESTIMATED_DEPARTURE_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE PASSENGER (
  ID INT AUTO_INCREMENT PRIMARY KEY,
  FIRST_NAME VARCHAR(256),
  LAST_NAME VARCHAR(256),
  MIDDLE_NAME VARCHAR(256),
  EMAIL VARCHAR(50),
  PHONE VARCHAR(10)
);

CREATE TABLE BUS_RESERVATION (
  ID INT AUTO_INCREMENT PRIMARY KEY,
  CHECKED_IN BOOLEAN,
  NUMBER_OF_BAGS INT,
  PASSENGER_ID INT,
  BUS_ENTITY_ID INT,
  CREATED TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (PASSENGER_ID) REFERENCES PASSENGER(ID) ON DELETE CASCADE,
  FOREIGN KEY (BUS_ENTITY_ID) REFERENCES BUS_ENTITY(ID)
);

INSERT INTO BUS_ENTITY
(BUS_NUMBER, OPERATING_BUS_STAND, DEPARTURE_CITY, ARRIVAL_CITY, DATE_OF_DEPARTURE, ESTIMATED_DEPARTURE_TIME)
VALUES
('BUS101', 'KSRTC', 'Kochi', 'Bangalore', '2026-02-01', CURRENT_TIMESTAMP),
('BUS202', 'TNSTC', 'Chennai', 'Madurai', '2026-02-02', CURRENT_TIMESTAMP),
('BUS303', 'APSRTC', 'Hyderabad', 'Vijayawada', '2026-02-03', CURRENT_TIMESTAMP);

INSERT INTO PASSENGER
(FIRST_NAME, LAST_NAME, MIDDLE_NAME, EMAIL, PHONE)
VALUES
('Arun', 'Kumar', 'R', 'arun.kumar@example.com', '9876543210'),
('Meera', 'Nair', 'S', 'meera.nair@example.com', '9123456789'),
('Rahul', 'Menon', 'P', 'rahul.menon@example.com', '9988776655');

INSERT INTO BUS_RESERVATION
(CHECKED_IN, NUMBER_OF_BAGS, PASSENGER_ID, BUS_ENTITY_ID)
VALUES
(1, 2, 1, 1),  -- Arun booked BUS101
(0, 1, 2, 2),  -- Meera booked BUS202
(1, 3, 3, 3);  -- Rahul booked BUS303



